/*
   int idCobro;
    int idPedido;
    int idMesero;
    int idMesa;
    Date fecha;
 */
package Vistas;


public class CobrosPagos extends javax.swing.JPanel {

    public CobrosPagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLELIMINAR = new javax.swing.JLabel();
        jLBUSCAR1 = new javax.swing.JLabel();
        jLAGREGAR = new javax.swing.JLabel();
        jLMODIFICAR = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextTOTAL3 = new javax.swing.JTextField();
        jTextTOTAL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextTOTAL1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextTOTAL2 = new javax.swing.JTextField();
        jRadioBuEfectivo = new javax.swing.JRadioButton();
        Tarjeta = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jComboBMESAS = new javax.swing.JComboBox<>();
        jComboBoxMESEROS = new javax.swing.JComboBox<>();
        jRadioBuPendiente = new javax.swing.JRadioButton();
        jRadioBuNOOPENd = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        jLabel5 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jLabelfondo = new javax.swing.JLabel();
        jPBACKfondo = new javax.swing.JPanel();
        jLBUSCAR4 = new javax.swing.JLabel();
        jLBUSCAR3 = new javax.swing.JLabel();
        jLBUSCAR2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLELIMINAR.setBackground(new java.awt.Color(204, 204, 204));
        jLELIMINAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLELIMINAR.setForeground(new java.awt.Color(51, 51, 51));
        jLELIMINAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Icono/menu_food_cafe_vintage_icon_147397.png"))); // NOI18N
        jLELIMINAR.setText("Balance");
        jLELIMINAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLELIMINAR.setOpaque(true);
        jLELIMINAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLELIMINARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLELIMINARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLELIMINARMouseExited(evt);
            }
        });
        add(jLELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 130, 70));

        jLBUSCAR1.setBackground(new java.awt.Color(204, 204, 204));
        jLBUSCAR1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLBUSCAR1.setForeground(new java.awt.Color(51, 51, 51));
        jLBUSCAR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBUSCAR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Icono/Ok_27007.png"))); // NOI18N
        jLBUSCAR1.setText("Pagado");
        jLBUSCAR1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLBUSCAR1.setOpaque(true);
        jLBUSCAR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBUSCAR1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBUSCAR1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBUSCAR1MouseExited(evt);
            }
        });
        add(jLBUSCAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 130, 70));

        jLAGREGAR.setBackground(new java.awt.Color(204, 204, 204));
        jLAGREGAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLAGREGAR.setForeground(new java.awt.Color(51, 51, 51));
        jLAGREGAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAGREGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Icono/mimetypes_spreadsheet_table_335.png"))); // NOI18N
        jLAGREGAR.setText("Recibo");
        jLAGREGAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLAGREGAR.setOpaque(true);
        jLAGREGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAGREGARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLAGREGARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLAGREGARMouseExited(evt);
            }
        });
        add(jLAGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 130, 70));

        jLMODIFICAR.setBackground(new java.awt.Color(204, 204, 204));
        jLMODIFICAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLMODIFICAR.setForeground(new java.awt.Color(51, 51, 51));
        jLMODIFICAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMODIFICAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Icono/Close_2_26986.png"))); // NOI18N
        jLMODIFICAR.setText("Cancelar");
        jLMODIFICAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLMODIFICAR.setOpaque(true);
        jLMODIFICAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMODIFICARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLMODIFICARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLMODIFICARMouseExited(evt);
            }
        });
        add(jLMODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 130, 70));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pedidos");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 120, 20));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 50, 20));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Dididir Cuenta");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jTextTOTAL3.setBackground(new java.awt.Color(243, 241, 244));
        jTextTOTAL3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextTOTAL3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextTOTAL3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextTOTAL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTOTAL3ActionPerformed(evt);
            }
        });
        add(jTextTOTAL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 40, -1));

        jTextTOTAL.setBackground(new java.awt.Color(243, 241, 244));
        jTextTOTAL.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextTOTAL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextTOTAL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTOTALActionPerformed(evt);
            }
        });
        add(jTextTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 90, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Caja");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 120, 20));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Su Pago");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 70, 20));

        jTextTOTAL1.setBackground(new java.awt.Color(243, 241, 244));
        jTextTOTAL1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextTOTAL1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextTOTAL1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextTOTAL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTOTAL1ActionPerformed(evt);
            }
        });
        add(jTextTOTAL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 90, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Vuelto");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 80, 20));

        jTextTOTAL2.setBackground(new java.awt.Color(243, 241, 244));
        jTextTOTAL2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextTOTAL2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextTOTAL2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextTOTAL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTOTAL2ActionPerformed(evt);
            }
        });
        add(jTextTOTAL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 90, -1));

        jRadioBuEfectivo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioBuEfectivo.setForeground(new java.awt.Color(51, 51, 51));
        jRadioBuEfectivo.setText("Efectivo");
        jRadioBuEfectivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jRadioBuEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 90, -1));

        Tarjeta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Tarjeta.setForeground(new java.awt.Color(51, 51, 51));
        Tarjeta.setText("Tarjeta +10%");
        Tarjeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetaActionPerformed(evt);
            }
        });
        add(Tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 120, -1));

        jTable2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IDcobro", "Idpedido", "idmesa", "idmesero", "total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 260, 210));

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IDcobro", "Idpedido", "idmesa", "idmesero", "total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 270, 290));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cuaderno-abierto-vacio_400.jpg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.white));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("  Busqueda  por  Hora  ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 20));

        jDateChooser2.setBackground(new java.awt.Color(204, 204, 204));
        jDateChooser2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Busqueda por Mesa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Busqueda por Mesero");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Busqueda por fecha");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(153, 153, 153));
        label1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label1.setText("Buscar");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 50, 20));

        jComboBMESAS.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBMESAS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesa n°1", "Mesa n°2", "Mesa n°3", "Mesa n°4", "Mesa n°5", "Mesa n°6", "Mesa n°7", "Mesa n°8", "Mesa n°9", "Mesa n°10", "Mesa n°11", "Mesa n°12", "Mesa n°13", "Mesa n°14", "Mesa n°15", "Mesa n°16", "Mesa n°17", "Mesa n°18", "Mesa n°19", "Mesa n°20", " " }));
        jComboBMESAS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jComboBMESAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, -1));

        jComboBoxMESEROS.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBoxMESEROS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lucas Aielo", "Alejandro Gaite", "Nahuel Gavino", "Francisco Andrian", " " }));
        jComboBoxMESEROS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jComboBoxMESEROS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, -1));

        jRadioBuPendiente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioBuPendiente.setForeground(new java.awt.Color(51, 51, 51));
        jRadioBuPendiente.setText("Pendiente");
        jRadioBuPendiente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jRadioBuPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 90, -1));

        jRadioBuNOOPENd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioBuNOOPENd.setForeground(new java.awt.Color(51, 51, 51));
        jRadioBuNOOPENd.setText("NoPendiente");
        jRadioBuNOOPENd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jRadioBuNOOPENd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBuNOOPENdActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioBuNOOPENd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 100, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Hs.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 30, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Hs.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 30, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("y las");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 30, -1));

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("23:30");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 20));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("18:00");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 20));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(153, 153, 153));
        label2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label2.setText("Buscar");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 50, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Entre las");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(153, 153, 153));
        label3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label3.setText("Buscar");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 50, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 410));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comidarap.png"))); // NOI18N
        jLabelfondo.setText("jLabel1");
        add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1000, 430));

        jPBACKfondo.setBackground(new java.awt.Color(204, 204, 204));
        jPBACKfondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPBACKfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPBACKfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 430));

        jLBUSCAR4.setBackground(new java.awt.Color(204, 204, 204));
        jLBUSCAR4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLBUSCAR4.setForeground(new java.awt.Color(51, 51, 51));
        jLBUSCAR4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBUSCAR4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Icono/search_magnifying_glass_icon_192631 (1).png"))); // NOI18N
        jLBUSCAR4.setText("Mesero");
        jLBUSCAR4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLBUSCAR4.setOpaque(true);
        jLBUSCAR4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBUSCAR4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBUSCAR4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBUSCAR4MouseExited(evt);
            }
        });
        add(jLBUSCAR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLBUSCAR3.setBackground(new java.awt.Color(204, 204, 204));
        jLBUSCAR3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLBUSCAR3.setForeground(new java.awt.Color(51, 51, 51));
        jLBUSCAR3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBUSCAR3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Icono/search_magnifying_glass_icon_192631 (1).png"))); // NOI18N
        jLBUSCAR3.setText("Pedido");
        jLBUSCAR3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLBUSCAR3.setOpaque(true);
        jLBUSCAR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBUSCAR3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBUSCAR3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBUSCAR3MouseExited(evt);
            }
        });
        add(jLBUSCAR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        jLBUSCAR2.setBackground(new java.awt.Color(204, 204, 204));
        jLBUSCAR2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLBUSCAR2.setForeground(new java.awt.Color(51, 51, 51));
        jLBUSCAR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBUSCAR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Icono/search_magnifying_glass_icon_192631 (1).png"))); // NOI18N
        jLBUSCAR2.setText("Mesas");
        jLBUSCAR2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLBUSCAR2.setOpaque(true);
        jLBUSCAR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBUSCAR2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBUSCAR2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBUSCAR2MouseExited(evt);
            }
        });
        add(jLBUSCAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLBUSCAR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR1MouseClicked

    private void jLBUSCAR1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR1MouseEntered

    private void jLBUSCAR1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR1MouseExited

    private void jLAGREGARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAGREGARMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLAGREGARMouseClicked

    private void jLAGREGARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAGREGARMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLAGREGARMouseEntered

    private void jLAGREGARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAGREGARMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLAGREGARMouseExited

    private void jLMODIFICARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMODIFICARMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLMODIFICARMouseClicked

    private void jLMODIFICARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMODIFICARMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLMODIFICARMouseEntered

    private void jLMODIFICARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMODIFICARMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLMODIFICARMouseExited

    private void jRadioBuNOOPENdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBuNOOPENdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBuNOOPENdActionPerformed

    private void jLBUSCAR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR2MouseClicked

    private void jLBUSCAR2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR2MouseEntered

    private void jLBUSCAR2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR2MouseExited

    private void jLBUSCAR3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR3MouseClicked

    private void jLBUSCAR3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR3MouseEntered

    private void jLBUSCAR3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR3MouseExited

    private void jLBUSCAR4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR4MouseClicked

    private void jLBUSCAR4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR4MouseEntered

    private void jLBUSCAR4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBUSCAR4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLBUSCAR4MouseExited

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLELIMINARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLELIMINARMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLELIMINARMouseExited

    private void jLELIMINARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLELIMINARMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLELIMINARMouseEntered

    private void jLELIMINARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLELIMINARMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLELIMINARMouseClicked

    private void jTextTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTOTALActionPerformed

    private void jTextTOTAL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTOTAL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTOTAL1ActionPerformed

    private void jTextTOTAL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTOTAL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTOTAL2ActionPerformed

    private void TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TarjetaActionPerformed

    private void jTextTOTAL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTOTAL3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTOTAL3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Tarjeta;
    private javax.swing.JComboBox<String> jComboBMESAS;
    private javax.swing.JComboBox<String> jComboBoxMESEROS;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLAGREGAR;
    private javax.swing.JLabel jLBUSCAR1;
    private javax.swing.JLabel jLBUSCAR2;
    private javax.swing.JLabel jLBUSCAR3;
    private javax.swing.JLabel jLBUSCAR4;
    private javax.swing.JLabel jLELIMINAR;
    private javax.swing.JLabel jLMODIFICAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JPanel jPBACKfondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioBuEfectivo;
    private javax.swing.JRadioButton jRadioBuNOOPENd;
    private javax.swing.JRadioButton jRadioBuPendiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextTOTAL;
    private javax.swing.JTextField jTextTOTAL1;
    private javax.swing.JTextField jTextTOTAL2;
    private javax.swing.JTextField jTextTOTAL3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
